# Remap prefix from 'C-b' to 'C-a'
unbind C-b

set-option -g prefix C-a
bind-key C-a send-prefix

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Enable focus-events tracking in tmux, required for autocommand events in Neovim
set-option -g focus-events on

# Set true color (fix colors)
set -ga terminal-overrides ",*256col*:Tc"

# Set start pane numbering at 1 instead of 0
set -g base-index 1
