[env]
TERM = 'xterm-256color'

[font]
normal = { family = "JetBrainsMonoNerdFont" }
size = 11

[colors.primary]
background = '#24283b'
foreground = '#a9b1d6'

[colors.normal]
black   = '#1f2335'
red     = '#c53b53'
green   = '#c3e88d'
yellow  = '#ffc777'
blue    = '#7aa2f7'
magenta = '#9d7cd8'
cyan    = '#41a6b5'
white   = '#c0caf5'

[window]
opacity = 0.9
