[env]
TERM = 'screen-256color'

[font]
# Any NerdFontMono
normal = { family = 'JetBrainsMonoNerdFontMono' }
size = 12

[window]
opacity = 0.8

[colors.primary]
foreground = '#e0def4'
background = '#191724'

[colors.normal]
black   = '#26233a'
red     = '#eb6f92'
green   = '#31748f'
yellow  = '#f6c177'
blue    = '#9ccfd8'
magenta = '#c4a7e7'
cyan    = '#ebbcba'
white   = '#e0def4'

[colors.bright]
black   = '#6e6a86'
red     = '#eb6f92'
green   = '#31748f'
yellow  = '#f6c177'
blue    = '#9ccfd8'
magenta = '#c4a7e7'
cyan    = '#ebbcba'
white   = '#e0def4'
